baseurl = "/"
title = "Alex Bass"

theme = "hugo-coder-portfolio"
googleAnalytics = "UA-194046200-1"

DefaultContentLanguage = "en"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

[params]
    author = "ALEX BASS"
    description = "Alex Bass, data, programming"
    keywords = "data,programming,visualization"
    info = "RESEARCH ANALYST"
    avatarurl = "images/alex.jpeg"
    footercontent = "Hello there! Check out the BLOG or PROJECT tabs for latest my thoughts and work 👌"

    hideCredits = true
    hideCopyright = true

    # Bottom sns share
    snsShare = true
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = false
    enableFacebookShare = false
    enableLinkedInShare = false
    
    thumbnail = "images/favicon1.jpeg"
    
    # Custom CSS
    custom_css = ["css/foo.css"]

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false
    
    enableEmoji = true


[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 1
    url = "https://twitter.com/acbass49"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/alex-bass-4a7465161/"
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 2
    url = "https://github.com/acbass49"


# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "about"

[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "post"

[[menu.main]]
    name = "Projects"
    weight = 3
    url  = "projects"
    
[[menu.main]]
    name = "CV"
    weight = 4
    url  = "files/cv.pdf"
    
[[menu.main]]
    name = "Contact"
    weight = 5
    url  = "contact"
